const fs = require('fs')
const generators = require('./generators')

function dumpEnum(src, enumName, dst) {
  fs.appendFileSync(dst, `public enum ${enumName} {\n`)

  src.forEach(({ name, id }) => {
    fs.appendFileSync(dst, `    ${name} = ${id},\n`)
  })

  fs.appendFileSync(dst, '};\n\n')
}

function dumpCs({ units, abilities, upgrades, buffs, effects }) {
  const dst = fs.openSync('./dist/sc2_typeenums.cs', 'w')

  fs.appendFileSync(
    dst,
    `/* 
Created ${new Date().toISOString()}

All units and abilities are represented as unsigned numbers in the StarCraft II engine. This file aims to provide
a type safe and named way of representing various game types. Entries in it are generated by a custom
utility located at https://github.com/cpp-sc2/codegen
*/
`
  )

  dumpEnum(units, 'UnitType', dst)
  dumpEnum(abilities, 'Ability', dst)
  dumpEnum(upgrades, 'Upgrade', dst)
  dumpEnum(buffs, 'Buff', dst)
  dumpEnum(effects, 'Effect', dst)

  fs.closeSync(dst)
}

module.exports = function generate(stableIDs) {
  const units = generators.generateUnits(stableIDs.Units)
  const abilities = generators.generateAbilities(stableIDs.Abilities)
  const upgrades = generators.generateUpgrades(stableIDs.Upgrades)
  const buffs = generators.generateBuffs(stableIDs.Buffs)
  const effects = generators.generateEffects(stableIDs.Effects)

  dumpCs({ units, abilities, upgrades, buffs, effects })
}
